services:
  db:
    image: postgres:16.0-alpine
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db_data:
